project:
  type: website

website:
  title: "quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
# https://jadeyryan.com/blog/2023-11-19_publish-quarto-website/#freeze-computations
execute:
  freeze: auto


